language: java
jdk:
- oraclejdk9
deploy:
  provider: releases
  api_key:
    secure: B0vwXgRhKEuULle+HfCbAwnEAoTKVwnqNXCFkrHIxVbkeoBfqFIohKwhbQiw0JlRRc+9WYVayNfOuw1Vn9Oa3Ny+uK0jvJjJjNtuj2zwyNnigW4F6pshduLzvNPqczwi4k2haAd1cF8mGSmTEChrSN1icehh6doM0mNfud7mk6WB69q6BRCbxzNbMe4d+BlZG+oJud4C6AKnf+Rf1Dry6lB6hz0YA92zLckatdOP322ow8VRaTZW83huyL5OBEjAgxkKKNILIpv8N1BSM3Dv6sOCxJJGUuCgMCMfrpI6MKB2LFEpGpNSTGQXD1nOv4TlFTYRfOrukqjA5ga8caWNF4Ul+he2hQ+UZbbWGF6dr+s+/I+MQbHz0UaFkh4hH/vQu6rPPjpaY1e9V6yXWTkdvZ4FCbSNIVY5cdjI4BlzUhOAtTa8ihut6vCtjm/nbwLow5NXKF5dwLJs1sy51PCxAp7XUz1Mq8pM4YfSKRNNtC1u+oqeJ1d2KjU8ApnFoEpv4Y8JMWFCU5tl5cyvKnXAVIXquwbJG2YRB8QEgTzOWRqnS05gAHgh6Qy99SMBNWWuedIP/xpeO0fCOze68xncDMi5dMRcI28Lo27PqCkqEVMpweWC1i6WBBao2rc4tRmHQpWu8Y3s9H5FYgx+Rnp8Wab96s8IQrkod8R6/Ciff3g=
  file: target/one_player_shutdown-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true
    repo: Dargmuesli/one-player-shutdown
notifications:
  email:
    on_success: never
    on_failure: always
