name: one-player-shutdown
main: de.jonas_thelemann.one_player_shutdown.OnePlayerShutdown
version: 1.0.1
description: Automatically shuts a Minecraft server down when only one player is connected.
author: Jonas Thelemann
website: jonas-thelemann.de
commands:
  oneplayershutdown:
    description: Commands for configuring automatic shutdown.
    usage: |
      /<command> [enable, start] - enable One-Player-Shutdown.
      /<command> [disable, stop] - disable One-Player-Shutdown.
      /<command> status - displays the current plugin configuration.
      /<command> timelimit <seconds> - set the shutdown's timelimit.
      /<command> reset - resets this plugin's configuration.
